# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Close Solved issues'
on:
  workflow_dispatch:
  schedule:
    # Hourly
    - cron: '0 * * * *'
# Remove all permissions by default. Actions are performed by Bitnami Bot
permissions: {}
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
        with:
          any-of-labels: 'solved'
          stale-issue-label: 'solved'
          days-before-stale: 0
          days-before-close: 0
          repo-token: ${{ secrets.BITNAMI_BOT_TOKEN }}