# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Comments based card movements'
on:
  issue_comment:
    types:
      - created
# Remove all permissions by default
permissions:
  pull-requests: write
  issues: write
jobs:
  call-comments-workflow:
    uses: bitnami/support/.github/workflows/comment-created.yml@main
    secrets: inherit