name: 'Move closed issues'
on:
  issues:
    types:
      - closed
  pull_request_target:
    types:
      - closed

permissions:
  issues: write
  repository-projects: write

jobs:
  send_to_solved:
    runs-on: ubuntu-latest
    steps:
      - name: Send to the Solved column
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ (!contains(fromJson(env.BITNAMI_TEAM), github.event.*.user.login)) }}
        with:
          project-name: Support
          # If the author comes from Bitnami, send it to Bitnami. Otherwise, all to Triage
          column-name: 'Solved'
          token: "${{ secrets.GHPROJECT_TOKEN }}"
          issue-number: ${{ github.event_name != 'issues' && github.event.number || github.event.issue.number }}
      - name: Solved labeling
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "solved"
          remove-labels: "in-progress, on-hold, triage"