name: '[Support] Move closed issues'
on:
  issues:
    types:
      - closed
  pull_request_target:
    types:
      - closed

permissions:
  issues: write
  repository-projects: write

concurrency:
  group: ${{ github.event_name != 'issues' && github.event.number || github.event.issue.number }}
  cancel-in-progress: false

jobs:
  send_to_solved:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
      - name: Preparing string variables
        run: |
          TRIAGE_TEAM_STRING=${TRIAGE_TEAM/[/}
          TRIAGE_TEAM_STRING=${TRIAGE_TEAM_STRING/]/}
          TRIAGE_TEAM_STRING=${TRIAGE_TEAM_STRING//'"'/}
          # creating env variable "on the fly"
          echo "TRIAGE_TEAM_STRING=$TRIAGE_TEAM_STRING" >> $GITHUB_ENV
      - name: Send to the Solved column
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Support
          # If the author comes from Bitnami, send it to Bitnami. Otherwise, all to Triage
          column-name: 'Solved'
          token: "${{ secrets.GHPROJECT_TOKEN }}"
          issue-number: ${{ github.event_name != 'issues' && github.event.number || github.event.issue.number }}
      - name: Solved labeling
        # Only if moved into Solved
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "solved"
          remove-labels: "in-progress, on-hold, triage"
