# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Review based card movements'
on:
  pull_request_target:
    types:
      - review_requested
      - synchronize
# Remove all permissions by default.
permissions: {}
jobs:
  call-pr-review-workflow:
    uses: bitnami/support/.github/workflows/pr-review-requested-sync.yml@main
    secrets: inherit