# This workflow is built to manage the triage support by using GH issues.
name: '[Support] Organize triage'
on:
  issues:
    types:
      - reopened
      - opened
  pull_request_target:
    types:
      - reopened
      - opened
# Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event_name != 'issues' && github.event.number || github.event.issue.number }}
jobs:
  # For any opened or reopened issue, should be sent into Triage
  send_to_board:
    name: Organize triage
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/
      - name: Get author
        id: get-issue
        run: |
          author="${{ github.event.issue != null && github.event.issue.user.login || github.event.pull_request.user.login }}"
          number="${{ github.event_name != 'issues' && github.event.number || github.event.issue.number }}"
          echo "author=${author}" >> $GITHUB_OUTPUT
          echo "number=${number}" >> $GITHUB_OUTPUT
      - name: Send to the board
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Support
          # If the author comes from Bitnami, send it to Bitnami. Otherwise, all to Triage
          column-name: ${{ (contains(fromJson(env.BITNAMI_TEAM), steps.get-issue.outputs.author)) && 'From Bitnami' || 'Triage' }}
          token: "${{ secrets.BITNAMI_BOT_TOKEN }}"
          issue-number: ${{ steps.get-issue.outputs.number }}